export const events = [
  {
    id: 1,
    title: "React Summit 2024",
    image: "/images/event1.png",
    slug: "react-summit-2024",
    location: "Amsterdam, Netherlands",
    date: "October 15-17, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    id: 2,
    title: "DevWorld Conference",
    image: "/images/event2.png",
    slug: "devworld-conference-2024",
    location: "San Francisco, CA",
    date: "November 5-7, 2024",
    time: "8:30 AM - 5:30 PM",
  },
  {
    id: 3,
    title: "Global Hackathon Challenge",
    image: "/images/event3.png",
    slug: "global-hackathon-2024",
    location: "Vancouver, Canada",
    date: "September 28-29, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    id: 4,
    title: "Next.js Conf 2024",
    image: "/images/event4.png",
    slug: "nextjs-conf-2024",
    location: "San Francisco, CA",
    date: "December 3-4, 2024",
    time: "10:00 AM - 6:00 PM",
  },
  {
    id: 5,
    title: "TechCrunch Disrupt",
    image: "/images/event5.png",
    slug: "techcrunch-disrupt-2024",
    location: "New York, NY",
    date: "October 28-30, 2024",
    time: "9:00 AM - 7:00 PM",
  },
  {
    id: 6,
    title: "AI & Machine Learning Summit",
    image: "/images/event6.png",
    slug: "ai-ml-summit-2024",
    location: "London, UK",
    date: "November 12-14, 2024",
    time: "8:00 AM - 6:00 PM",
  },

  {
    id: 7,
    title: "Blockchain Technology Conference",
    image: "/images/event-full.png",
    slug: "blockchain-technology-conference-2024",
    location: "Tokyo, Japan",
    date: "December 10-12, 2024",
    time: "9:00 AM - 6:00 PM",
  },
 
];
